# SonarQube Project Configuration
sonar.projectKey=git-sonar
sonar.projectName=git-sonar
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.js,**/dist/**,**/build/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8
