name: SonarQube Scan & Quality Gate Check

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  sonarqube:
    name: SonarQube Vulnerability Scan
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarQube Scan & Quality Gate Check
        shell: powershell
        run: |
          docker run --rm -v "${{ github.workspace }}:/usr/src" sonarsource/sonar-scanner-cli "-Dsonar.host.url=http://host.docker.internal:9000" "-Dsonar.token=${{ secrets.SONAR_TOKEN }}" "-Dsonar.projectKey=git-sonar" "-Dsonar.qualitygate.wait=true"
